# Process Tomography

This is a notebook for the process tomography

## Environment Configuration

Import regular packages

In [1]:
import qutip as qt
import numpy as np

Add relative path

In [2]:
import sys
import os
sys.path.append(os.path.join('..','src'))

Import main package

In [3]:
import Metrology as My

## Demo

### Set input 

#### Input $\rho_{in} s$ 


In [4]:
rho1i=qt.Qobj([[1,0],[0,0]])
rho2i=qt.Qobj([[0,0],[0,1]])
rho3i=qt.Qobj([[0.5,0.5],[0.5,0.5]])
rho4i=qt.Qobj([[0.5,-0.5j],[0.5j,0.5]])
rho_in=[rho1i,rho2i,rho3i,rho4i]
print(rho_in)

[Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 0.]], Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 0.]
 [0. 1.]], Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.5 0.5]
 [0.5 0.5]], Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.5+0.j  0. -0.5j]
 [0. +0.5j 0.5+0.j ]]]


#### Output $\rho_{out} s$

In [5]:
rho1o=qt.Qobj([[1,0],[0,0]])
rho2o=qt.Qobj([[0.5,0],[0,0.5]])
rho3o=qt.Qobj([[3/4,1/np.sqrt(8)],[1/np.sqrt(8),1/4]])
rho4o=qt.Qobj([[3/4,-1j/np.sqrt(8)],[1j/np.sqrt(8),1/4]])
rho_out=[rho1o,rho2o,rho3o,rho4o]
print(rho_out)

[Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 0.]], Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.5 0. ]
 [0.  0.5]], Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.75       0.35355339]
 [0.35355339 0.25      ]], Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.75+0.j         0.  -0.35355339j]
 [0.  +0.35355339j 0.25+0.j        ]]]


#### Tomography basis $\tilde{E}$

In [6]:
basis=[qt.qeye(2),qt.sigmax(),\
        qt.sigmay(),qt.sigmaz()]
basis=[0.5*base for base in basis]
print(basis)

[Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.5 0. ]
 [0.  0.5]], Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.  0.5]
 [0.5 0. ]], Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j  0.-0.5j]
 [0.+0.5j 0.+0.j ]], Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 0.5  0. ]
 [ 0.  -0.5]]]


### Perform state tomography

Calculate $\chi$ and $E$

In [7]:
chi,E=My.qubits_process_tomography(rho_in,rho_out,basis)

In [8]:
print(chi)

[[ 2.91421356+0.j   0.        +0.j   0.        +0.j   0.5       +0.j ]
 [ 0.        +0.j   0.5       +0.j  -0.        -0.5j  0.        +0.j ]
 [ 0.        +0.j   0.        +0.5j  0.5       +0.j   0.        +0.j ]
 [ 0.5       +0.j   0.        +0.j   0.        -0.j   0.08578644+0.j ]]


In [9]:
print(E)

[Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 0.]
 [0. 0.]], Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 4.56253019e-09  0.00000000e+00]
 [ 0.00000000e+00 -6.45239207e-09]], Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0.+0.j         0.+0.70710678j]
 [0.+0.j         0.+0.j        ]], Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[-1.          0.        ]
 [ 0.         -0.70710678]]]


### Check if it is correct

In [10]:
for rhoi in rho_in:
    print(My.apply_process_E(E,rhoi))


Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 0.]]
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.5 0. ]
 [0.  0.5]]
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.75       0.35355339]
 [0.35355339 0.25      ]]
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.75+0.j         0.  -0.35355339j]
 [0.  +0.35355339j 0.25+0.j        ]]


In [11]:
for rhoi in rho_in:
    print(My.apply_process_Chi(chi,basis,rhoi))

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 0.]]
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.5 0. ]
 [0.  0.5]]
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.75       0.35355339]
 [0.35355339 0.25      ]]
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.75+0.j         0.  -0.35355339j]
 [0.  +0.35355339j 0.25+0.j        ]]


In [17]:
check=0
for op in E:
    check=check+op.dag()*op
print(check)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]
